import { useQuery, useQueryClient } from '@tanstack/react-query'
import { Activity, ArrowDownRight, ArrowRight, ArrowUpRight, Bell, Check, ChevronDown, CircleAlert, CircleHelp, Clock3, DatabaseBackup, Globe2, LayoutDashboard, LifeBuoy, LockKeyhole, LogOut, Menu, Plus, Search, Settings2, ShieldCheck, Sparkles, Ticket, Users, Wrench, X } from 'lucide-react'
import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { api, currentUser, login, type User } from './api'
import WorkspacePage from './WorkspacePage'

type Summary={websites:number;healthy:number;open_tickets:number;uptime_percent:number|null;checks_total:number;average_response_ms:number|null;daily_uptime:{date:string;checks:number;uptime_percent:number|null}[];recent_tickets:{id:number;number:string;subject:string;status:string;priority:string;website:{name:string}}[];recent_websites:{id:number;name:string;url:string;status:string;is_up:boolean|null;response_ms:number|null}[]}
const demo:Summary={websites:8,healthy:7,open_tickets:3,uptime_percent:99.9,checks_total:420,average_response_ms:342,daily_uptime:[],recent_tickets:[{id:1,number:'SC-2026-00421',subject:'Contact form is not sending submissions',status:'in_progress',priority:'high',website:{name:'Northstar Studio'}},{id:2,number:'SC-2026-00420',subject:'Update team page with new portraits',status:'waiting_for_client',priority:'normal',website:{name:'Northstar Studio'}},{id:3,number:'SC-2026-00418',subject:'Review SSL certificate renewal',status:'open',priority:'urgent',website:{name:'Harbor & Pine'}}],recent_websites:[{id:1,name:'Northstar Studio',url:'northstar.design',status:'active',is_up:true,response_ms:342},{id:2,name:'Harbor & Pine',url:'harborandpine.com',status:'active',is_up:true,response_ms:518},{id:3,name:'Goodfield Journal',url:'goodfield.co',status:'active',is_up:false,response_ms:0},{id:4,name:'Morrow Architecture',url:'morrow.studio',status:'active',is_up:true,response_ms:277}]}
const nav=[['Overview',LayoutDashboard],['Websites',Globe2],['Tickets',Ticket],['Maintenance',Wrench],['Backups',DatabaseBackup],['Incidents',CircleAlert],['Team',Users],['Reports',Activity]] as const
function App(){
 const [user,setUser]=useState<User|null>(null),[loginOpen,setLoginOpen]=useState(false),[active,setActive]=useState('Overview'),[mobile,setMobile]=useState(false)
 useEffect(()=>{currentUser().then(setUser).catch(()=>{})},[])
 const summary=useQuery({queryKey:['dashboard',user?.id],queryFn:async()=>(await api.get<{data:Summary}>('/api/v1/dashboard')).data.data,enabled:!!user})
 const dashboard=summary.data??demo
 const responseLabel=summary.data?(summary.data.average_response_ms?`${Math.round(summary.data.average_response_ms)} ms`:'—'):'342 ms'
 const uptimeLabel=summary.data?(summary.data.uptime_percent===null?'No data':`${summary.data.uptime_percent}%`):'99.9%'
 const healthScore=summary.data?(summary.data.uptime_percent===null?'—':String(Math.round(summary.data.uptime_percent))):'99'
 const healthPercentSuffix=healthScore==='—'?'':'%'
 const healthTitle=summary.data?(summary.data.checks_total?'Monitoring is active':'Waiting for the first health check'):'Everything looks good'
 const healthCaption=summary.data?`${summary.data.checks_total} checks in the last 30 days`:'Across 8 monitored websites'
 const uptimeTrendLabel=summary.data?(summary.data.uptime_percent===null?'No data':`${summary.data.uptime_percent}%`):'99.92%'
 if(window.location.pathname==='/accept-invitation') return <AcceptInvitation/>
 return <><div className="topline"><span><Sparkles size={13}/> Your websites, looked after.</span><a href="#how">See how SiteCare works <ArrowRight size={13}/></a></div>
 <div className="app-shell"><aside className={`sidebar ${mobile?'show':''}`}><div className="brand"><span className="brand-mark"><Activity size={19}/></span><span>sitecare<span className="brand-dot">.</span></span><button className="icon-button close-menu" onClick={()=>setMobile(false)}><X size={18}/></button></div><div className="workspace-label">WORKSPACE</div><button className="workspace"><span className="workspace-avatar">N</span><span className="workspace-copy"><b>{user?.role==='admin'?'SiteCare Agency':'Northstar Studio'}</b><small>{user?.role==='admin'?'Administrator workspace':'Client workspace'}</small></span><ChevronDown size={15}/></button><nav className="side-nav">{nav.filter(([label])=>label!=='Team'||user?.role==='admin').map(([label,Icon])=><button key={label} className={active===label?'selected':''} onClick={()=>{setActive(label);setMobile(false)}}><Icon size={17}/>{label}{label==='Tickets'&&<i>{dashboard.open_tickets}</i>}</button>)}</nav><div className="sidebar-bottom"><button onClick={()=>setActive('Settings')}><Settings2 size={17}/> Settings</button><button><CircleHelp size={17}/> Help centre</button><div className="side-note"><span className="note-icon"><ShieldCheck size={16}/></span><b>Your sites are in good hands</b><small>Checks run every 15 minutes.</small><a href="#health">View health report <ArrowRight size={13}/></a></div><div className="profile"><span className="profile-avatar">{user?.name?.[0]??'J'}</span><span><b>{user?.name??'Jamie Parker'}</b><small>{user?.role??'Client'}</small></span><button className="icon-button" title="Sign out" onClick={async()=>{await api.post('/api/v1/auth/logout').catch(()=>{});setUser(null)}}><LogOut size={16}/></button></div></div></aside>
 <main className="main"><header className="header"><button className="icon-button open-menu" onClick={()=>setMobile(true)}><Menu size={19}/></button><div className="crumb">Workspace <span>/</span> <b>{active}</b></div><div className="header-actions"><div className="searchbox"><Search size={16}/><input aria-label="Search" placeholder="Search anything..."/><kbd>⌘ K</kbd></div>{user?<NotificationBell/>:<button className="icon-button notification" aria-label="Notifications"><Bell size={18}/></button>}{user?<button className="help-link"><CircleHelp size={16}/> Help</button>:<button className="help-link" onClick={()=>setLoginOpen(true)}><LockKeyhole size={15}/> Sign in</button>}</div></header>
 <div className="content">{active==="Overview"?<><div className="welcome-row"><div><div className="eyebrow"><span className="live-dot"/> TUESDAY, OCTOBER 1</div><h1>Good morning, {user?.name?.split(' ')[0]??'Jamie'} <span className="wave">✳</span></h1><p>Here’s what’s happening with your websites today.</p></div><button className="primary-btn" onClick={()=>setActive('Websites')}><Plus size={16}/> Add or review websites</button></div>
 <div className="stat-grid"><Stat icon={<Globe2/>} label="Managed websites" value={String(dashboard.websites).padStart(2,"0")} meta="Across your organisation"/><Stat icon={<Activity/>} label="Sites online" value={String(dashboard.healthy).padStart(2,"0")} meta={<><span className="positive"><ArrowUpRight size={14}/> {uptimeLabel}</span> average uptime</>}/><Stat icon={<LifeBuoy/>} label="Open tickets" value={String(dashboard.open_tickets).padStart(2,"0")} meta={<><span className="attention">Open items need attention</span></>}/><Stat icon={<Clock3/>} label="Avg. page response" value={responseLabel} meta={<><span className="positive"><ArrowDownRight size={14}/> {dashboard.checks_total} checks in 30 days</span></>}/></div>
 <div className="dashboard-grid"><section className="card health-card" id="health"><div className="card-head"><div><h2>Website health</h2><p>A quick look at your managed sites.</p></div><button className="text-button" onClick={()=>setActive('Websites')}>All websites <ArrowRight size={15}/></button></div><div className="health-summary"><div className="health-score"><div className="score-ring"><b>{healthScore}<span>{healthPercentSuffix}</span></b></div><div><b>{healthTitle}</b><small>{healthCaption}</small></div></div><div className="health-legend"><span><i className="legend-green"/> {dashboard.healthy} healthy</span><span><i className="legend-amber"/> {Math.max(0,dashboard.websites-dashboard.healthy)} not online</span></div></div><div className="site-list">{dashboard.recent_websites.map((site,i)=><div className="site-row" key={site.id}><span className={`site-icon site-${i}`}><Globe2 size={17}/></span><span className="site-name"><b>{site.name}</b><small>{site.url}</small></span><span className={`site-state ${site.is_up?'up':'down'}`}><i/>{site.is_up?'Operational':'Issue detected'}</span><span className="response">{site.is_up?`${site.response_ms} ms`:'—'}<small>response</small></span><button className="row-arrow" aria-label={`Open ${site.name}`} onClick={()=>setActive('Websites')}><ArrowRight size={15}/></button></div>)}</div><button className="mobile-all" onClick={()=>setActive('Websites')}>View all websites <ArrowRight size={15}/></button></section>
 <section className="card tickets-card"><div className="card-head"><div><h2>Recent tickets <span className="count-badge">3</span></h2><p>Updates from your support team.</p></div><button className="text-button" onClick={()=>setActive('Tickets')}>View all <ArrowRight size={15}/></button></div><div className="ticket-list">{dashboard.recent_tickets.map(t=><button className="ticket-row" key={t.id} onClick={()=>setActive('Tickets')}><div className="ticket-top"><span>{t.number}</span><span className={`priority ${t.priority}`}>{t.priority==='urgent'?'Urgent':t.priority==='high'?'High':'Normal'}</span></div><b>{t.subject}</b><div className="ticket-meta"><span>{t.website.name}</span><span className={`ticket-status ${t.status}`}>{t.status.replaceAll('_',' ')}</span></div></button>)}</div><button className="new-ticket" onClick={()=>setActive('Tickets')}><Plus size={15}/> Create a support ticket</button></section>
 </div><div className="lower-grid"><section className="card uptime-card"><div className="card-head"><div><h2>Uptime this month</h2><p>Your websites are being checked around the clock.</p></div><button className="period">Last 30 days <ChevronDown size={14}/></button></div><div className="chart-info"><b>{uptimeTrendLabel}</b><span className="positive"> <ArrowUpRight size={14}/> 0.08% <small>vs. last month</small></span></div><div className="chart" aria-label="Uptime was stable across the last 30 days">{Array.from({length:30},(_,i)=><span key={i} className={i===17?'chart-warning':''} style={{height:`${38+((i*17)%42)}%`}}/>)}</div><div className="chart-axis"><span>Sep 1</span><span>Sep 15</span><span>Today</span></div></section><section className="card activity-card"><div className="card-head"><div><h2>Recent activity</h2><p>Latest updates from your team.</p></div><button className="more-btn" aria-label="More activity">···</button></div><div className="activity-list"><ActivityRow color="green" icon={<Check size={14}/>} title="Website check completed" detail="Northstar Studio · All clear" time="12 min ago"/><ActivityRow color="purple" icon={<Wrench size={14}/>} title="Work in progress" detail="Contact form investigation" time="1 hour ago"/><ActivityRow color="orange" icon={<Ticket size={14}/>} title="Ticket updated" detail="SSL certificate renewal · Open" time="3 hours ago"/></div></section></div><footer><span>© 2026 SiteCare</span><span><i/> All systems operational</span><a href="#privacy">Privacy & security</a></footer>
 </>:<WorkspacePage active={active} user={user} onSignIn={()=>setLoginOpen(true)}/>}</div></main></div>{mobile&&<button className="backdrop" aria-label="Close menu" onClick={()=>setMobile(false)}/>}<LoginDialog open={loginOpen} close={()=>setLoginOpen(false)} done={setUser}/></>
}
function Stat({icon,label,value,meta}:{icon:React.ReactNode;label:string;value:string;meta:React.ReactNode}){return <div className="stat-card"><div className="stat-top"><span className="stat-icon">{icon}</span><span className="stat-more">···</span></div><small>{label}</small><div className="stat-value">{value}</div><div className="stat-meta">{meta}</div></div>}
function ActivityRow({icon,color,title,detail,time}:{icon:React.ReactNode;color:string;title:string;detail:string;time:string}){return <div className="activity-row"><span className={`activity-icon ${color}`}>{icon}</span><span className="activity-copy"><b>{title}</b><small>{detail}</small></span><time>{time}</time></div>}
function NotificationBell(){const client=useQueryClient();const[open,setOpen]=useState(false);const notices=useQuery({queryKey:['notifications'],queryFn:async()=>(await api.get<{data:{id:string;data:{title:string;message:string;url:string};read_at:string|null;created_at:string}[]}>('/api/v1/notifications')).data.data,refetchInterval:60000});const unread=notices.data?.filter(item=>!item.read_at).length??0;async function openNotice(id:string){try{await api.patch(`/api/v1/notifications/${id}`,{});await client.invalidateQueries({queryKey:['notifications']})}catch{setOpen(false)}setOpen(false)}return <div className="notification-menu"><button className="icon-button notification" aria-label={`Notifications${unread?`, ${unread} unread`:''}`} aria-expanded={open} onClick={()=>setOpen(value=>!value)}><Bell size={18}/>{unread>0&&<i/>}</button>{open&&<section className="notification-popover" aria-label="Notifications"><div className="notification-heading"><b>Notifications</b><span>{unread} unread</span></div>{notices.isLoading?<p className="empty-state">Loading…</p>:notices.data?.length?notices.data.map(item=><a href={item.data.url||'/'} key={item.id} className={`notification-item ${item.read_at?'read':''}`} onClick={()=>openNotice(item.id)}><b>{item.data.title}</b><span>{item.data.message}</span><time>{new Date(item.created_at).toLocaleString()}</time></a>):<p className="empty-state">You’re all caught up.</p>}</section>}</div>}
function LoginDialog({open,close,done}:{open:boolean;close:()=>void;done:(user:User)=>void}){const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[error,setError]=useState('');const[busy,setBusy]=useState(false);const navigate=useNavigate();if(!open)return null;return <div className="modal-shade" onMouseDown={e=>e.target===e.currentTarget&&close()}><form className="login-card" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{done(await login(email,password));close();navigate('/')}catch{setError('Sign-in failed. Check your details and make sure the API is running.')}finally{setBusy(false)}}}><button type="button" className="modal-close icon-button" onClick={close}><X size={18}/></button><span className="brand-mark"><Activity size={19}/></span><p className="eyebrow">WELCOME BACK</p><h2>Sign in to SiteCare</h2><p>Pick up right where your websites need you.</p><label>Email address<input required type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@company.com"/></label><label>Password<input required type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Your password"/></label>{error&&<div className="form-error">{error}</div>}<button className="primary-btn full" disabled={busy}>{busy?'Signing in…':'Sign in'} <ArrowRight size={16}/></button><small className="login-foot">Invited to SiteCare? Accept your invitation to get started.</small></form></div>}
function AcceptInvitation(){const params=new URLSearchParams(window.location.search);const[token]=useState(params.get('token')??'');const[email]=useState(params.get('email')??'');const[name,setName]=useState('');const[password,setPassword]=useState('');const[confirm,setConfirm]=useState('');const[error,setError]=useState('');const[accepted,setAccepted]=useState(false);return <div className="modal-shade"><form className="login-card" onSubmit={async e=>{e.preventDefault();setError('');try{await api.post('/api/v1/invitations/accept',{token,email,name,password,password_confirmation:confirm});setAccepted(true)}catch{setError('This invitation could not be accepted. Check that the link is valid and has not expired.')}}}><span className="brand-mark"><Activity size={19}/></span><p className="eyebrow">SITECARE INVITATION</p><h2>{accepted?'You’re all set':'Create your account'}</h2><p>{accepted?'Your account is ready. Sign in to open your workspace.':'Set a name and password to join your organisation.'}</p>{!accepted&&<><label>Name<input required maxLength={120} value={name} onChange={e=>setName(e.target.value)} autoComplete="name"/></label><label>Email address<input required type="email" value={email} readOnly/></label><label>Password<input required type="password" minLength={12} value={password} onChange={e=>setPassword(e.target.value)} autoComplete="new-password"/></label><label>Confirm password<input required type="password" minLength={12} value={confirm} onChange={e=>setConfirm(e.target.value)} autoComplete="new-password"/></label>{error&&<div className="form-error">{error}</div>}<button className="primary-btn full">Accept invitation <ArrowRight size={16}/></button></>}{accepted&&<a className="primary-btn full" href="/">Continue to SiteCare <ArrowRight size={16}/></a>}</form></div>}
export default App
