import { useQuery } from '@tanstack/react-query'
import { Activity, ArrowDownRight, ArrowRight, ArrowUpRight, Bell, Check, ChevronDown, CircleHelp, Clock3, Globe2, LayoutDashboard, LifeBuoy, LockKeyhole, LogOut, Menu, Plus, Search, Settings2, ShieldCheck, Sparkles, Ticket, Wrench, X } from 'lucide-react'
import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { api, currentUser, login, type User } from './api'

type Summary={websites:number;healthy:number;open_tickets:number;recent_tickets:{id:number;number:string;subject:string;status:string;priority:string;website:{name:string}}[];recent_websites:{id:number;name:string;url:string;status:string;is_up:boolean|null;response_ms:number|null}[]}
const demo:Summary={websites:8,healthy:7,open_tickets:3,recent_tickets:[{id:1,number:'SC-2026-00421',subject:'Contact form is not sending submissions',status:'in_progress',priority:'high',website:{name:'Northstar Studio'}},{id:2,number:'SC-2026-00420',subject:'Update team page with new portraits',status:'waiting_for_client',priority:'normal',website:{name:'Northstar Studio'}},{id:3,number:'SC-2026-00418',subject:'Review SSL certificate renewal',status:'open',priority:'urgent',website:{name:'Harbor & Pine'}}],recent_websites:[{id:1,name:'Northstar Studio',url:'northstar.design',status:'active',is_up:true,response_ms:342},{id:2,name:'Harbor & Pine',url:'harborandpine.com',status:'active',is_up:true,response_ms:518},{id:3,name:'Goodfield Journal',url:'goodfield.co',status:'active',is_up:false,response_ms:0},{id:4,name:'Morrow Architecture',url:'morrow.studio',status:'active',is_up:true,response_ms:277}]}
const nav=[['Overview',LayoutDashboard],['Websites',Globe2],['Tickets',Ticket],['Maintenance',Wrench],['Reports',Activity]] as const
function App(){
 const [user,setUser]=useState<User|null>(null),[loginOpen,setLoginOpen]=useState(false),[active,setActive]=useState('Overview'),[mobile,setMobile]=useState(false)
 useEffect(()=>{currentUser().then(setUser).catch(()=>{})},[])
 const summary=useQuery({queryKey:['dashboard',user?.id],queryFn:async()=>(await api.get<{data:Summary}>('/api/v1/dashboard')).data.data,enabled:!!user})
 const dashboard=summary.data??demo
 return <><div className="topline"><span><Sparkles size={13}/> Your websites, looked after.</span><a href="#how">See how SiteCare works <ArrowRight size={13}/></a></div>
 <div className="app-shell"><aside className={`sidebar ${mobile?'show':''}`}><div className="brand"><span className="brand-mark"><Activity size={19}/></span><span>sitecare<span className="brand-dot">.</span></span><button className="icon-button close-menu" onClick={()=>setMobile(false)}><X size={18}/></button></div><div className="workspace-label">WORKSPACE</div><button className="workspace"><span className="workspace-avatar">N</span><span className="workspace-copy"><b>{user?.role==='admin'?'SiteCare Agency':'Northstar Studio'}</b><small>{user?.role==='admin'?'Administrator workspace':'Client workspace'}</small></span><ChevronDown size={15}/></button><nav className="side-nav">{nav.map(([label,Icon])=><button key={label} className={active===label?'selected':''} onClick={()=>{setActive(label);setMobile(false)}}><Icon size={17}/>{label}{label==='Tickets'&&<i>3</i>}</button>)}</nav><div className="sidebar-bottom"><button onClick={()=>setActive('Settings')}><Settings2 size={17}/> Settings</button><button><CircleHelp size={17}/> Help centre</button><div className="side-note"><span className="note-icon"><ShieldCheck size={16}/></span><b>Your sites are in good hands</b><small>Checks run every 15 minutes.</small><a href="#health">View health report <ArrowRight size={13}/></a></div><div className="profile"><span className="profile-avatar">{user?.name?.[0]??'J'}</span><span><b>{user?.name??'Jamie Parker'}</b><small>{user?.role??'Client'}</small></span><button className="icon-button" title="Sign out" onClick={async()=>{await api.post('/api/v1/auth/logout').catch(()=>{});setUser(null)}}><LogOut size={16}/></button></div></div></aside>
 <main className="main"><header className="header"><button className="icon-button open-menu" onClick={()=>setMobile(true)}><Menu size={19}/></button><div className="crumb">Workspace <span>/</span> <b>{active}</b></div><div className="header-actions"><div className="searchbox"><Search size={16}/><input aria-label="Search" placeholder="Search anything..."/><kbd>⌘ K</kbd></div><button className="icon-button notification" aria-label="Notifications"><Bell size={18}/><i/></button>{user?<button className="help-link"><CircleHelp size={16}/> Help</button>:<button className="help-link" onClick={()=>setLoginOpen(true)}><LockKeyhole size={15}/> Sign in</button>}</div></header>
 <div className="content"><div className="welcome-row"><div><div className="eyebrow"><span className="live-dot"/> TUESDAY, OCTOBER 1</div><h1>Good morning, {user?.name?.split(' ')[0]??'Jamie'} <span className="wave">✳</span></h1><p>Here’s what’s happening with your websites today.</p></div><button className="primary-btn" onClick={()=>setActive('Websites')}><Plus size={16}/> Add a website</button></div>
 <div className="stat-grid"><Stat icon={<Globe2/>} label="Managed websites" value="08" meta="Across your organisation"/><Stat icon={<Activity/>} label="Sites online" value="07" meta={<><span className="positive"><ArrowUpRight size={14}/> 99.9%</span> average uptime</>}/><Stat icon={<LifeBuoy/>} label="Open tickets" value="03" meta={<><span className="attention">1 needs your reply</span></>}/><Stat icon={<Clock3/>} label="Avg. response time" value="2.4h" meta={<><span className="positive"><ArrowDownRight size={14}/> 18%</span> this month</>}/></div>
 <div className="dashboard-grid"><section className="card health-card" id="health"><div className="card-head"><div><h2>Website health</h2><p>A quick look at your managed sites.</p></div><button className="text-button" onClick={()=>setActive('Websites')}>All websites <ArrowRight size={15}/></button></div><div className="health-summary"><div className="health-score"><div className="score-ring"><b>99<span>%</span></b></div><div><b>Everything looks good</b><small>Across 8 monitored websites</small></div></div><div className="health-legend"><span><i className="legend-green"/> 7 healthy</span><span><i className="legend-amber"/> 1 needs attention</span></div></div><div className="site-list">{dashboard.recent_websites.map((site,i)=><div className="site-row" key={site.id}><span className={`site-icon site-${i}`}><Globe2 size={17}/></span><span className="site-name"><b>{site.name}</b><small>{site.url}</small></span><span className={`site-state ${site.is_up?'up':'down'}`}><i/>{site.is_up?'Operational':'Issue detected'}</span><span className="response">{site.is_up?`${site.response_ms} ms`:'—'}<small>response</small></span><button className="row-arrow" aria-label={`Open ${site.name}`} onClick={()=>setActive('Websites')}><ArrowRight size={15}/></button></div>)}</div><button className="mobile-all" onClick={()=>setActive('Websites')}>View all websites <ArrowRight size={15}/></button></section>
 <section className="card tickets-card"><div className="card-head"><div><h2>Recent tickets <span className="count-badge">3</span></h2><p>Updates from your support team.</p></div><button className="text-button" onClick={()=>setActive('Tickets')}>View all <ArrowRight size={15}/></button></div><div className="ticket-list">{dashboard.recent_tickets.map(t=><button className="ticket-row" key={t.id} onClick={()=>setActive('Tickets')}><div className="ticket-top"><span>{t.number}</span><span className={`priority ${t.priority}`}>{t.priority==='urgent'?'Urgent':t.priority==='high'?'High':'Normal'}</span></div><b>{t.subject}</b><div className="ticket-meta"><span>{t.website.name}</span><span className={`ticket-status ${t.status}`}>{t.status.replaceAll('_',' ')}</span></div></button>)}</div><button className="new-ticket" onClick={()=>setActive('Tickets')}><Plus size={15}/> Create a support ticket</button></section>
 </div><div className="lower-grid"><section className="card uptime-card"><div className="card-head"><div><h2>Uptime this month</h2><p>Your websites are being checked around the clock.</p></div><button className="period">Last 30 days <ChevronDown size={14}/></button></div><div className="chart-info"><b>99.92%</b><span className="positive"> <ArrowUpRight size={14}/> 0.08% <small>vs. last month</small></span></div><div className="chart" aria-label="Uptime was stable across the last 30 days">{Array.from({length:30},(_,i)=><span key={i} className={i===17?'chart-warning':''} style={{height:`${38+((i*17)%42)}%`}}/>)}</div><div className="chart-axis"><span>Sep 1</span><span>Sep 15</span><span>Today</span></div></section><section className="card activity-card"><div className="card-head"><div><h2>Recent activity</h2><p>Latest updates from your team.</p></div><button className="more-btn" aria-label="More activity">···</button></div><div className="activity-list"><ActivityRow color="green" icon={<Check size={14}/>} title="Website check completed" detail="Northstar Studio · All clear" time="12 min ago"/><ActivityRow color="purple" icon={<Wrench size={14}/>} title="Work in progress" detail="Contact form investigation" time="1 hour ago"/><ActivityRow color="orange" icon={<Ticket size={14}/>} title="Ticket updated" detail="SSL certificate renewal · Open" time="3 hours ago"/></div></section></div><footer><span>© 2026 SiteCare</span><span><i/> All systems operational</span><a href="#privacy">Privacy & security</a></footer>
 </div></main></div>{mobile&&<button className="backdrop" aria-label="Close menu" onClick={()=>setMobile(false)}/>}<LoginDialog open={loginOpen} close={()=>setLoginOpen(false)} done={setUser}/></>
}
function Stat({icon,label,value,meta}:{icon:React.ReactNode;label:string;value:string;meta:React.ReactNode}){return <div className="stat-card"><div className="stat-top"><span className="stat-icon">{icon}</span><span className="stat-more">···</span></div><small>{label}</small><div className="stat-value">{value}</div><div className="stat-meta">{meta}</div></div>}
function ActivityRow({icon,color,title,detail,time}:{icon:React.ReactNode;color:string;title:string;detail:string;time:string}){return <div className="activity-row"><span className={`activity-icon ${color}`}>{icon}</span><span className="activity-copy"><b>{title}</b><small>{detail}</small></span><time>{time}</time></div>}
function LoginDialog({open,close,done}:{open:boolean;close:()=>void;done:(user:User)=>void}){const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[error,setError]=useState('');const[busy,setBusy]=useState(false);const navigate=useNavigate();if(!open)return null;return <div className="modal-shade" onMouseDown={e=>e.target===e.currentTarget&&close()}><form className="login-card" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{done(await login(email,password));close();navigate('/')}catch{setError('Sign-in failed. Check your details and make sure the API is running.')}finally{setBusy(false)}}}><button type="button" className="modal-close icon-button" onClick={close}><X size={18}/></button><span className="brand-mark"><Activity size={19}/></span><p className="eyebrow">WELCOME BACK</p><h2>Sign in to SiteCare</h2><p>Pick up right where your websites need you.</p><label>Email address<input required type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@company.com"/></label><label>Password<input required type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Your password"/></label>{error&&<div className="form-error">{error}</div>}<button className="primary-btn full" disabled={busy}>{busy?'Signing in…':'Sign in'} <ArrowRight size={16}/></button><small className="login-foot">Invited to SiteCare? Accept your invitation to get started.</small></form></div>}
export default App
